FROM biltudas1/mxe:qt-static

# Install Poetry
RUN wget https://install.python-poetry.org -O - | python3 -
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /mnt

# Install Packages
COPY pyproject.toml .
COPY poetry.lock .
RUN poetry install --with dev --no-root

ENTRYPOINT [ "/bin/bash", "debug.sh" ]