name: "Docker Build & Publish"

on:
  workflow_dispatch:
    inputs:
      run_docker:
        description: 'Set to true to run Docker build'
        required: true
        default: 'false'
      dockerfile_path:
        description: 'Path to Dockerfile to use'
        required: true
        default: 'docker/Dockerfile.mxe-qt6-dynamic'
      docker_image:
        description: 'Image:Tag name to publish'
        required: true
        default: 'biltudas1/mxe:qt-dynamic'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_docker == 'true' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ github.event.inputs.dockerfile_path }}
          push: true
          tags: ${{ github.event.inputs.docker_image }}
